---
language: python
python: "2.7"

language: ruby
rvm:
  - 1.9.3

before_install:
  - sudo apt-get update -qq

gemfile:
  - Gemfile

install:
  # Install Ansible.
  - sudo pip install ansible
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tasks/main.yml --syntax-check --extra-vars 'gem_path=/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/gem'"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -vvvv -i tests/inventory tasks/main.yml --connection=local --sudo --extra-vars 'gem_path=/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/gem'"
